apiVersion: apps/v1
kind: Deployment
metadata:
  name: frpc-deployment
spec:
  selector:
    matchLabels:
      app: frpc
  replicas: 1
  template:
    metadata:
      labels:
        app: frpc
    spec:
      nodeSelector:  # 指定节点
        kubernetes.io/hostname: lab3
      hostNetwork: true
      containers:
      - name: frpc-lab3-con
        image: snowdreamtech/frpc
        volumeMounts:
        - name: frpc-config-lab3-con
          mountPath: /etc/frp/frpc.toml
          subPath: lab3-con
          readOnly: true
      - name: frpc-lab3-raw
        image: snowdreamtech/frpc
        volumeMounts:
        - name: frpc-config-lab3-raw
          mountPath: /etc/frp/frpc.toml
          subPath: lab3-raw
          readOnly: true
      volumes:
      - name: frpc-config-lab3-con
        configMap:
          name: frpc-conf
      - name: frpc-config-lab3-raw
        configMap:
          name: frpc-conf
