# mysql-deployment.yaml

apiVersion: v1
kind: Pod
metadata:
  name: mysql-lab3
  labels:
    app: mysql-lab3
spec:
  hostNetwork: true  # 启用 HostNetwork 模式
  nodeSelector:
    kubernetes.io/hostname: lab3
  containers:
  - name: mysql-lab3-con
    image: mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: mysqltest
# ---
# # mysql-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-lab3
# spec:
#   type: NodePort
#   selector:
#     app: mysql-lab3 # to pod label
#   ports:
#   - name: mysql
#     port: 3306
#     nodePort: 31766
#     targetPort: 3306